table Dim_Piloto
	lineageTag: a2f8fd21-4008-4038-ac10-662f974f72e2

	column driverId
		dataType: int64
		formatString: 0
		lineageTag: 1ddc5636-6045-4ac6-8aba-7513442c4b3a
		summarizeBy: none
		sourceColumn: driverId

		annotation SummarizationSetBy = Automatic

	column driverRef
		dataType: string
		lineageTag: bc7c15ab-ff03-447c-a87f-21968db3050c
		summarizeBy: none
		sourceColumn: driverRef

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: a23a7879-8d56-453a-860b-739f094ca4ae
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: 0ca9c096-6dbd-45a5-820c-6fa07bd2afb4
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column forename
		dataType: string
		lineageTag: 7baaab3e-0347-452c-9de7-97681a24441b
		summarizeBy: none
		sourceColumn: forename

		annotation SummarizationSetBy = Automatic

	column surname
		dataType: string
		lineageTag: 97478eb0-1590-4959-9f6e-7ac8034cce94
		summarizeBy: none
		sourceColumn: surname

		annotation SummarizationSetBy = Automatic

	column dob
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24a8c752-8f8b-46e5-a4e5-95ded18d91f9
		summarizeBy: none
		sourceColumn: dob

		variation Variation
			isDefault
			relationship: d6d677c8-132a-494b-8a8e-03860ae50096
			defaultHierarchy: LocalDateTable_b7b25017-8a53-4f4c-a420-0976c96fa22d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column nationality
		dataType: string
		lineageTag: 231b9c48-fdd1-4ee7-81db-3ce7897f03bb
		summarizeBy: none
		sourceColumn: nationality

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 68d20848-ec87-46ee-9d16-e41abc7a4f83
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition Dim_Piloto = m
		mode: import
		source =
				let
				  Origem = Csv.Document(File.Contents("C:\Users\ferna\Downloads\archiveF1\drivers.csv"), [Delimiter = ",", Columns = 9, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(Origem, [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"driverId", Int64.Type}, {"driverRef", type text}, {"number", type text}, {"code", type text}, {"forename", type text}, {"surname", type text}, {"dob", type date}, {"nationality", type text}, {"url", type text}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

