table Dim_Equipe
	lineageTag: 5d04657a-72b5-4005-bdca-5902b5179e22

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 233e5619-021a-460e-9de4-bf06879714db
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column constructorRef
		dataType: string
		lineageTag: 58e45d41-d679-4928-a69e-893e45edf445
		summarizeBy: none
		sourceColumn: constructorRef

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: b872e58e-5744-4f3a-9958-86bca063e6b7
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column nationality
		dataType: string
		lineageTag: 6426f17d-c209-46a4-bddb-6db5c2e078ee
		summarizeBy: none
		sourceColumn: nationality

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 7f04dbc2-5bb0-4d9e-89c8-dfd29112eb9c
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition Dim_Equipe = m
		mode: import
		source =
				let
				  Origem = Csv.Document(File.Contents("C:\Users\ferna\Downloads\archiveF1\constructors.csv"), [Delimiter = ",", Columns = 5, QuoteStyle = QuoteStyle.None]),
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(Origem, [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"constructorId", Int64.Type}, {"constructorRef", type text}, {"name", type text}, {"nationality", type text}, {"url", type text}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

