table Dim_Corrida
	lineageTag: ce61d862-9023-4d87-8fd6-306e90749781

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 6f8756f7-2028-44d1-9062-cb2ed8aa7476
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 134cfb04-bd8c-4fb1-811e-0a0c7518ecb9
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column round
		dataType: int64
		formatString: 0
		lineageTag: 889f00f6-bd20-4a4a-b59f-a65c9f99e2ed
		summarizeBy: sum
		sourceColumn: round

		annotation SummarizationSetBy = Automatic

	column circuitId
		dataType: int64
		formatString: 0
		lineageTag: 37f099dc-cf1d-4dcf-9e1d-7cffadf7f675
		summarizeBy: none
		sourceColumn: circuitId

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: b0485ec4-afa4-49a7-89ea-77542212210a
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b80998ee-199c-45f6-8737-6e4d992eedc4
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column time
		dataType: string
		lineageTag: 186d0430-487b-4ed0-9d23-fdc56f68bc06
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 8e8d8d6d-9305-4828-a9c8-d4a603f90013
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition Dim_Corrida = m
		mode: import
		source =
				let
				  Origem = Csv.Document(File.Contents("C:\Users\ferna\Downloads\archiveF1\races.csv"), [Delimiter = ",", Columns = 18, QuoteStyle = QuoteStyle.None]),
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(Origem, [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"raceId", Int64.Type}, {"year", Int64.Type}, {"round", Int64.Type}, {"circuitId", Int64.Type}, {"name", type text}, {"date", type date}, {"time", type text}, {"url", type text}, {"fp1_date", type text}, {"fp1_time", type text}, {"fp2_date", type text}, {"fp2_time", type text}, {"fp3_date", type text}, {"fp3_time", type text}, {"quali_date", type text}, {"quali_time", type text}, {"sprint_date", type text}, {"sprint_time", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo de coluna alterado",{"fp1_date", "fp1_time", "fp2_date", "fp2_time", "fp3_date", "fp3_time", "quali_date", "quali_time", "sprint_date", "sprint_time"})
				in
				  #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

