table Medidas
	lineageTag: 8b1c396f-d24a-4407-9425-02124cffe614

	measure 'Total Pontos' = SUM(Fato_Resultados[points])
		formatString: 0
		displayFolder: Medidas base
		lineageTag: e61fdfea-fa70-4309-88de-f1965e6dbcc2

	measure 'Total Corridas' = DISTINCTCOUNT(Fato_Resultados[raceId])
		formatString: 0
		displayFolder: Medidas base
		lineageTag: 58d621e0-4578-4a05-92ee-0b3f382d71c3

	measure Vitórias =
			
			CALCULATE(
			    COUNTROWS(Fato_Resultados),
			    Fato_Resultados[position] = 1
			)
		formatString: 0
		displayFolder: Medidas base
		lineageTag: 526ec212-db9c-4b50-8469-c70f04656ff1

	measure Pódios =
			
			CALCULATE(
			    COUNTROWS(Fato_Resultados),
			    Fato_Resultados[position] <= 3
			)
		formatString: 0
		displayFolder: Medidas base
		lineageTag: a30b41ec-7237-49b3-b868-a41f28071fe3

	measure 'Posições Ganhas' =
			
			SUMX(
			    FILTER(Fato_Resultados, NOT(ISBLANK(Fato_Resultados[position]))),
			    Fato_Resultados[grid] - Fato_Resultados[position]
			)
		displayFolder: Medidas performance
		lineageTag: 4443306d-a42e-495d-ae73-d30fd9b4a9d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DNFs = ```
			
			CALCULATE(
			    COUNTROWS(Fato_Resultados),
			    FILTER(Dim_Status, Dim_Status[status] <> "Finished" 
			        && NOT(CONTAINSSTRING(Dim_Status[status], "Lap")))
			)
			```
		formatString: 0
		displayFolder: Medidas performance
		lineageTag: 93959f37-93b4-4b19-8553-972b9c29a604

	measure 'Taxa de DNF %' =
			
			DIVIDE([DNFs], [Total Corridas], 0)
		displayFolder: Medidas performance
		lineageTag: b822de87-f865-49eb-83d5-d7febadf1800

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pontos por Corrida' =
			
			DIVIDE([Total Pontos], [Total Corridas], 0)
		displayFolder: Medidas performance
		lineageTag: 4cd4b374-c45b-4c38-9eac-8a5a0e0aa9c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pontos Acumulados Temporada' =
			
			CALCULATE(
			    [Total Pontos],
			    FILTER(
			        ALLSELECTED(Dim_Calendario),
			        Dim_Calendario[Date] <= MAX(Dim_Calendario[Date])
			    )
			)
		formatString: 0
		displayFolder: Medidas performance
		lineageTag: e5a658e1-1265-45b6-a305-cc0ef1d47a4e

	measure 'Ranking Construtor' =
			
			IF(
			    HASONEVALUE(Dim_Equipe[name]),
			    RANKX(
			        ALLSELECTED(Dim_Equipe[name]),
			        [Total Pontos],
			        ,
			        DESC,
			        Dense
			    )
			)
		formatString: 0
		displayFolder: Construtores
		lineageTag: 50f633ac-be34-493c-bd05-52f9486ebc75

	measure 'Construtor Campeão' =
			
			VAR TabelaRank =
			    ADDCOLUMNS(
			        ALLSELECTED(Dim_Equipe[name]),
			        "@Pontos", [Total Pontos]
			    )
			VAR Topo =
			    TOPN(1, TabelaRank, [@Pontos], DESC)
			RETURN
			    MAXX(Topo, Dim_Equipe[name])
		displayFolder: Construtores
		lineageTag: 830bca0b-4c4c-421c-b4eb-9b8199f39b8c

	measure 'Pontos do Campeão' =
			
			MAXX(
			    TOPN(
			        1,
			        ADDCOLUMNS(ALLSELECTED(Dim_Equipe[name]), "@P", [Total Pontos]),
			        [@P], DESC
			    ),
			    [@P]
			)
		formatString: 0
		displayFolder: Construtores
		lineageTag: 3fe6ee08-4a57-4585-9d72-e0373a33a89f

	measure 'Equipes que Pontuaram' =
			
			CALCULATE(
			    DISTINCTCOUNT(Fato_Resultados[constructorId]),
			    Fato_Resultados[points] > 0
			)
		formatString: 0
		displayFolder: Construtores
		lineageTag: 1be46c20-d333-47a3-af3c-da618698090a

	measure 'Vitórias 1-2' =
			
			-- corridas onde a equipe fez dobradinha (1º e 2º)
			SUMX(
			    VALUES(Fato_Resultados[raceId]),
			    VAR Pos1e2 =
			        CALCULATE(
			            COUNTROWS(Fato_Resultados),
			            Fato_Resultados[position] <= 2
			        )
			    RETURN IF(Pos1e2 = 2, 1, 0)
			)
		formatString: 0
		displayFolder: Construtores
		lineageTag: 64ac4853-646e-427e-8f9f-50da9b2168eb

	measure 'Equipe Mais Confiável' =
			
			VAR TabelaDNF =
			    ADDCOLUMNS(
			        ALLSELECTED(Dim_Equipe[name]),
			        "@Taxa", [Taxa de DNF %]
			    )
			VAR Menor =
			    TOPN(1, TabelaDNF, [@Taxa], ASC)
			RETURN
			    MAXX(Menor, Dim_Equipe[name])
		displayFolder: Construtores
		lineageTag: c4176786-b3e5-4f05-a25e-d517d5e40fa5

	partition Medidas = m
		mode: import
		source =
				let
				  Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Colunas Removidas" = Table.RemoveColumns(Origem,{"Coluna 1"})
				in
				  #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

